// Originally generated by Lovable; hand-edited since issue #102 to fail loudly
// on missing configuration rather than deep inside createClient.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Which Supabase this app talks to is the difference between local, dev and
  // prod data. Guessing is not an option, and an unset value should say so by
  // name rather than surfacing as an opaque auth failure later.
  throw new Error(
    "VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must both be set. " +
      "Copy .env.example to .env (local), or set them in this deployment's " +
      "environment variables."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});